#!/bin/bash
SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
full_path=$(realpath $0)
dir_path=$(dirname $full_path)
cd $dir_path
java -Duser.dir=$SCRIPT_DIR -jar ../Trains/target/xclients.jar $1 $2